#!/usr/bin/env bash
# Transfer files

params=$#

if [ $params -le 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking no -i $1 $3@$2:$4'~/'
fi

#scp file.txt remote_username@10.10.0.2:/remote/directory/newfilename.txtCopied!

