#!/usr/bin/env bash
# Redirect configuration

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

new_conf="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default

sudo service nginx restart

