#!/usr/bin/env bash
# NGINX

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

new_string="\\\thostname magm.tech;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
path='/etc/nginx/sites-available/default'
sed -i "24i $new_string" $path

sudo service nginx restart

