#!/usr/bin/env bash
# NGINX

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html

new_conf="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

newhttp="\\\tadd_header X-Served-By \$hostname;\n"
sudo sed -i "34i $newhttp" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
