#!/usr/bin/env bash
# Configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

path="/etc/haproxy/haproxy.cfg"
echo "
frontend http
	bind *:80
	mode http
	default_backend icap_pool
backend icap_pool
	balance roundrobin
	mode http
	server 3332-web-01 35.237.25.66:80 check
	server 3332-web-02 34.234.71.240:80 check" | sudo tee -a $path > /dev/null

sudo service haproxy start
sudo service nginx restart
