#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# But before ten line prints "Hi"

x=1
while [ $x -le 10 ]
do
    if [[ $x == 10 ]]; then
        echo "Hi"
    fi
    echo "Best School"
    ((x++))
done