#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Display "bad luck" in 4th iteration
# Display "good luck" in 8th iteration

x=1
while [ $x -le 10 ]
do
    if [[ $x == 4 ]]; then
        echo "bad luck"
    elif [[ $x == 8 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x++))
done