#!/usr/bin/env bash
# This script is displaying number from 1 until 20

x=1
while [ $x -le 20 ]
do
    echo $x

    case $x in
    "4") echo -e "bad luck from China";;
    "9") echo -e "bad luck from Japan";;
    "17") echo -e "bad luck from Italy";;
    esac

    ((x++))
done