#!/usr/bin/env bash
# Display the time for 12 hours and 59 minuntes

x=0
y=1
while [ $x -le 12 ]
do
    echo "Hour:" $x
    while [ $y -le 59 ]
    do
        echo $y

        if [[ $y == 59 ]]; then
            y=1
            break
        fi
        ((y++))
    done

    ((x++))
done